export interface ItemResaultPrice {
  pricesClass: {
    resultPrice: number;
    price: number;
    priceVat: number;
    disPrice: number;
    priceAvgShipp: number;
  };
  id: number;
  parentId: number;
  parentSid: string;
  sort: number;
  title: string;
  titleEn: string | null;
  dateTime: string;
  product: boolean;
  service: boolean;
  percentWarehouse: number;
  percentTransit: number;
  modelId: number;
  attributeIds: string;
  showWebsite: boolean;
  stopProduction: boolean;
  complementary: string | null;
  accessWorkGroupId: string;
  attributeTitle: string;
  attributeGroupTitle: string;
  valueId: number;
  valueTitle: string;
  priceId: number;
  activateWarehouseProcessing: boolean;
  activateSchedule: boolean;
  codeAccSupplier: number;
  floatSupplier: number;
  codeAccSeller: number;
  floatSeller: number;
  companyId: number;
  priceBase: number;
  priceBaseVat: number;
  activateWarehouse: boolean;
  shippingStartTimeWarehouse: number;
  shippingEndTimeWarehouse: number;
  factoryLoadingCost: number;
  shippingCost: number;
  activateInstallment: boolean;
  percentagePayInstallments: number;
  installmentsId: number;
  priceBasePreSell: number;
  priceBaseVatPreSell: number;
  dueDayPreSell: number;
  activatePreSell: boolean;
  activateTransit: boolean;
  percentageTransit: number;
  shippingStartTimeTransit: number;
  shippingEndTimeTransit: number;
  lastPriceInquiry: string | null;
  weight: number;
  length: number;
  width: number;
  height: number;
  pricesDateTime: string;
  pricesDateTimeCreate: string;
  warehouseId: number;
  warehouseTitle: string;
  codeAccWarehouse: number;
  floatIdWarehouse: number;
  longitudeWarehouse: number;
  latitudeWarehouse: number;
  elevationWarehouse: number;
  unlimitedInventory: boolean;
  escrowBalance: number;
  fare: number;
  overheadCost: number;
  unloadingCost: number;
  percentage: number;
  costPriceWarehouse: number;
  costPriceTransit: number;
  priceWarehouse: number;
  priceAlternate: number;
  pricePreSellTransit: number;
  priceTransit: number;
  titleCompany: string;
  titleEnCompany: string | null;
  descriptionCompany: string | null;
  sloganCompany: string | null;
  priorityCompany: boolean;
  longitudeCompany: number;
  latitudeCompany: number;
  elevationCompany: number;
  isClosedCompany: boolean;
  codeAccSellerTitle: string | null;
  ladingCapacity: number;
  shippingTimeAlternate: string | null;
  limitNumberUserAccountAlternate: number;
  limitNumberUserAccount: number;
  limitNumberUserAccountTransit: number;
  limitNumberUserAccountPreSell: number;
  ididentityWarehouse: number;
  percentageDiscount: number;
  lowestNumberOfDiscount: number;
  percentageDiscount1: number;
  lowestNumberOfDiscount1: number;
  percentageDiscount2: number;
  lowestNumberOfDiscount2: number;
  promotionId: number;
  codeAccPromotion: number;
  floatIdPromotion: number;
  promotionTitle: string;
  descriptionDiscount: string;
  descriptionDiscount1: string | null;
  descriptionDiscount2: string | null;
  promotionUserAccountClubMember: boolean;
  promotionDiscountCode: string | null;
  promotionQuantityPerUserAccount: number;
  promotionDailyPeriod: boolean;
  promotionMonthlyPeriod: boolean;
  promotionTimeKeeper: boolean;
  promotionMajor: boolean;
  promotionStartDateTime: string;
  promotionExpireDateTime: string | null;
  promotionMinimumInvoiceAmount: number;
  ididentityDiscount: number;
  discountPriceWarehouse: number;
  discountPriceWarehouse1: number;
  discountPriceWarehouse2: number;
  activateAlternate: boolean;
  dependentOnInventoryInWarehouse: number;
  virtualWarehouse: boolean;
  vehicleId: number;
  delayTimeLadingInCompany: number;
  delayTimeInCompany: number;
  fareDelayTimeLadingInCompany: number;
  fareDelayTimeInCompany: number;
  archived: boolean;
  unitRatio: number;
  unitCost: number;
  roundCapacity: boolean;
  decimalCapacity: boolean;
  overload: number;
  valueIdBase: number;
  valueTitleBase: string;
}
